import 'dotenv/config'

const PORT = process.env.PORT || 8000
const APP_ENV = process.env.APP_ENV
const APP_URL = process.env.APP_URL
const ORIGIN_URLS = process.env.ORIGIN_URLS
const MONGODB_USERNAME = process.env.MONGODB_USERNAME
const MONGODB_PASSWORD = process.env.MONGODB_PASSWORD
const MONGODB_DB_NAME = process.env.MONGODB_DB_NAME
const VERIFICATION_TOKEN_SIGNATURE = process.env.VERIFICATION_TOKEN_SIGNATURE
const VERIFICATION_TOKEN_EXPIRE = process.env.VERIFICATION_TOKEN_EXPIRE
const ACCESS_TOKEN_SIGNATURE = process.env.ACCESS_TOKEN_SIGNATURE
const ACCESS_TOKEN_EXPIRE = process.env.ACCESS_TOKEN_EXPIRE
const REFRESH_TOKEN_SIGNATURE = process.env.REFRESH_TOKEN_SIGNATURE
const REFRESH_TOKEN_EXPIRE = process.env.REFRESH_TOKEN_EXPIRE
const EMAIL_USERNAME = process.env.EMAIL_USERNAME
const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD
const EMAIL_HOST = process.env.EMAIL_HOST
const EMAIL_PORT = process.env.EMAIL_PORT
const EMAIL_SERVICE = process.env.EMAIL_SERVICE
const EMAIL_SECURE = process.env.EMAIL_SECURE

export {
    ACCESS_TOKEN_EXPIRE, ACCESS_TOKEN_SIGNATURE, APP_ENV,
    APP_URL, EMAIL_HOST, EMAIL_PASSWORD, EMAIL_PORT, EMAIL_SECURE, EMAIL_SERVICE, EMAIL_USERNAME, MONGODB_DB_NAME, MONGODB_PASSWORD, MONGODB_USERNAME, ORIGIN_URLS, PORT, REFRESH_TOKEN_EXPIRE, REFRESH_TOKEN_SIGNATURE, VERIFICATION_TOKEN_EXPIRE, VERIFICATION_TOKEN_SIGNATURE
}

